/*
 * THIS FILE WAS GENERATED BY "@atproto/lex". DO NOT EDIT.
 */

import { l } from '@atproto/lex'

const $nsid = 'pub.leaflet.blocks.image'

type $nsid = typeof $nsid

export { $nsid }

type Main = {
  $type?: 'pub.leaflet.blocks.image'

  /**
   * Alt text description of the image, for accessibility.
   */
  alt?: string
  image: l.BlobRef
  aspectRatio: AspectRatio
}

export type { Main }

const main = /*#__PURE__*/ l.typedObject<Main>(
  $nsid,
  'main',
  /*#__PURE__*/ l.object({
    alt: /*#__PURE__*/ l.optional(/*#__PURE__*/ l.string()),
    image: /*#__PURE__*/ l.blob({ accept: ['image/*'], maxSize: 1000000 }),
    aspectRatio: /*#__PURE__*/ l.ref<AspectRatio>((() => aspectRatio) as any),
  }),
)

export { main }

const $type = $nsid

type $type = typeof $type

export { $type }

export const $isTypeOf = /*#__PURE__*/ main.isTypeOf.bind(main)
export const $build = /*#__PURE__*/ main.build.bind(main)
export const $assert = /*#__PURE__*/ main.assert.bind(main)
export const $check = /*#__PURE__*/ main.check.bind(main)
export const $cast = /*#__PURE__*/ main.cast.bind(main)
export const $ifMatches = /*#__PURE__*/ main.ifMatches.bind(main)
export const $matches = /*#__PURE__*/ main.matches.bind(main)
export const $parse = /*#__PURE__*/ main.parse.bind(main)
export const $safeParse = /*#__PURE__*/ main.safeParse.bind(main)
export const $validate = /*#__PURE__*/ main.validate.bind(main)
export const $safeValidate = /*#__PURE__*/ main.safeValidate.bind(main)

type AspectRatio = {
  $type?: 'pub.leaflet.blocks.image#aspectRatio'
  width: number
  height: number
}

export type { AspectRatio }

const aspectRatio = /*#__PURE__*/ l.typedObject<AspectRatio>(
  $nsid,
  'aspectRatio',
  /*#__PURE__*/ l.object({
    width: /*#__PURE__*/ l.integer(),
    height: /*#__PURE__*/ l.integer(),
  }),
)

export { aspectRatio }
