/*
 * THIS FILE WAS GENERATED BY "@atproto/lex". DO NOT EDIT.
 */

import { l } from '@atproto/lex'
import * as BlocksText from './text.defs'
import * as BlocksHeader from './header.defs'
import * as BlocksImage from './image.defs'
import * as BlocksOrderedList from './orderedList.defs'

const $nsid = 'pub.leaflet.blocks.unorderedList'

type $nsid = typeof $nsid

export { $nsid }

type Main = { $type?: 'pub.leaflet.blocks.unorderedList'; children: ListItem[] }

export type { Main }

const main = /*#__PURE__*/ l.typedObject<Main>(
  $nsid,
  'main',
  /*#__PURE__*/ l.object({
    children: /*#__PURE__*/ l.array(
      /*#__PURE__*/ l.ref<ListItem>((() => listItem) as any),
    ),
  }),
)

export { main }

const $type = $nsid

type $type = typeof $type

export { $type }

export const $isTypeOf = /*#__PURE__*/ main.isTypeOf.bind(main)
export const $build = /*#__PURE__*/ main.build.bind(main)
export const $assert = /*#__PURE__*/ main.assert.bind(main)
export const $check = /*#__PURE__*/ main.check.bind(main)
export const $cast = /*#__PURE__*/ main.cast.bind(main)
export const $ifMatches = /*#__PURE__*/ main.ifMatches.bind(main)
export const $matches = /*#__PURE__*/ main.matches.bind(main)
export const $parse = /*#__PURE__*/ main.parse.bind(main)
export const $safeParse = /*#__PURE__*/ main.safeParse.bind(main)
export const $validate = /*#__PURE__*/ main.validate.bind(main)
export const $safeValidate = /*#__PURE__*/ main.safeValidate.bind(main)

type ListItem = {
  $type?: 'pub.leaflet.blocks.unorderedList#listItem'
  content:
    | l.$Typed<BlocksText.Main>
    | l.$Typed<BlocksHeader.Main>
    | l.$Typed<BlocksImage.Main>
    | l.Unknown$TypedObject

  /**
   * Nested unordered list items. Mutually exclusive with orderedListChildren; if both are present, children takes precedence.
   */
  children?: ListItem[]

  /**
   * Nested ordered list items. Mutually exclusive with children; if both are present, children takes precedence.
   */
  orderedListChildren?: BlocksOrderedList.Main
}

export type { ListItem }

const listItem = /*#__PURE__*/ l.typedObject<ListItem>(
  $nsid,
  'listItem',
  /*#__PURE__*/ l.object({
    content: /*#__PURE__*/ l.typedUnion(
      [
        /*#__PURE__*/ l.typedRef<BlocksText.Main>(
          (() => BlocksText.main) as any,
        ),
        /*#__PURE__*/ l.typedRef<BlocksHeader.Main>(
          (() => BlocksHeader.main) as any,
        ),
        /*#__PURE__*/ l.typedRef<BlocksImage.Main>(
          (() => BlocksImage.main) as any,
        ),
      ],
      false,
    ),
    children: /*#__PURE__*/ l.optional(
      /*#__PURE__*/ l.array(
        /*#__PURE__*/ l.ref<ListItem>((() => listItem) as any),
      ),
    ),
    orderedListChildren: /*#__PURE__*/ l.optional(
      /*#__PURE__*/ l.ref<BlocksOrderedList.Main>(
        (() => BlocksOrderedList.main) as any,
      ),
    ),
  }),
)

export { listItem }
