/*
 * THIS FILE WAS GENERATED BY "@atproto/lex". DO NOT EDIT.
 */

import { l } from '@atproto/lex'

const $nsid = 'pub.leaflet.richtext.facet'

type $nsid = typeof $nsid

export { $nsid }

/** Facet feature for an identifier. Used for linking to a segment */
type Id = { $type?: 'pub.leaflet.richtext.facet#id'; id?: string }

export type { Id }

/** Facet feature for an identifier. Used for linking to a segment */
const id = /*#__PURE__*/ l.typedObject<Id>(
  $nsid,
  'id',
  /*#__PURE__*/ l.object({
    id: /*#__PURE__*/ l.optional(/*#__PURE__*/ l.string()),
  }),
)

export { id }

/** Facet feature for bold text */
type Bold = { $type?: 'pub.leaflet.richtext.facet#bold' }

export type { Bold }

/** Facet feature for bold text */
const bold = /*#__PURE__*/ l.typedObject<Bold>(
  $nsid,
  'bold',
  /*#__PURE__*/ l.object({}),
)

export { bold }

/** Facet feature for inline code. */
type Code = { $type?: 'pub.leaflet.richtext.facet#code' }

export type { Code }

/** Facet feature for inline code. */
const code = /*#__PURE__*/ l.typedObject<Code>(
  $nsid,
  'code',
  /*#__PURE__*/ l.object({}),
)

export { code }

/** Facet feature for a URL. The text URL may have been simplified or truncated, but the facet reference should be a complete URL. */
type Link = { $type?: 'pub.leaflet.richtext.facet#link'; uri: string }

export type { Link }

/** Facet feature for a URL. The text URL may have been simplified or truncated, but the facet reference should be a complete URL. */
const link = /*#__PURE__*/ l.typedObject<Link>(
  $nsid,
  'link',
  /*#__PURE__*/ l.object({ uri: /*#__PURE__*/ l.string() }),
)

export { link }

/** Annotation of a sub-string within rich text. */
type Main = {
  $type?: 'pub.leaflet.richtext.facet'
  index: ByteSlice
  features: (
    | l.$Typed<Link>
    | l.$Typed<DidMention>
    | l.$Typed<AtMention>
    | l.$Typed<Code>
    | l.$Typed<Highlight>
    | l.$Typed<Underline>
    | l.$Typed<Strikethrough>
    | l.$Typed<Id>
    | l.$Typed<Bold>
    | l.$Typed<Italic>
    | l.$Typed<Footnote>
    | l.Unknown$TypedObject
  )[]
}

export type { Main }

/** Annotation of a sub-string within rich text. */
const main = /*#__PURE__*/ l.typedObject<Main>(
  $nsid,
  'main',
  /*#__PURE__*/ l.object({
    index: /*#__PURE__*/ l.ref<ByteSlice>((() => byteSlice) as any),
    features: /*#__PURE__*/ l.array(
      /*#__PURE__*/ l.typedUnion(
        [
          /*#__PURE__*/ l.typedRef<Link>((() => link) as any),
          /*#__PURE__*/ l.typedRef<DidMention>((() => didMention) as any),
          /*#__PURE__*/ l.typedRef<AtMention>((() => atMention) as any),
          /*#__PURE__*/ l.typedRef<Code>((() => code) as any),
          /*#__PURE__*/ l.typedRef<Highlight>((() => highlight) as any),
          /*#__PURE__*/ l.typedRef<Underline>((() => underline) as any),
          /*#__PURE__*/ l.typedRef<Strikethrough>((() => strikethrough) as any),
          /*#__PURE__*/ l.typedRef<Id>((() => id) as any),
          /*#__PURE__*/ l.typedRef<Bold>((() => bold) as any),
          /*#__PURE__*/ l.typedRef<Italic>((() => italic) as any),
          /*#__PURE__*/ l.typedRef<Footnote>((() => footnote) as any),
        ],
        false,
      ),
    ),
  }),
)

export { main }

const $type = $nsid

type $type = typeof $type

export { $type }

export const $isTypeOf = /*#__PURE__*/ main.isTypeOf.bind(main)
export const $build = /*#__PURE__*/ main.build.bind(main)
export const $assert = /*#__PURE__*/ main.assert.bind(main)
export const $check = /*#__PURE__*/ main.check.bind(main)
export const $cast = /*#__PURE__*/ main.cast.bind(main)
export const $ifMatches = /*#__PURE__*/ main.ifMatches.bind(main)
export const $matches = /*#__PURE__*/ main.matches.bind(main)
export const $parse = /*#__PURE__*/ main.parse.bind(main)
export const $safeParse = /*#__PURE__*/ main.safeParse.bind(main)
export const $validate = /*#__PURE__*/ main.validate.bind(main)
export const $safeValidate = /*#__PURE__*/ main.safeValidate.bind(main)

/** Facet feature for italic text */
type Italic = { $type?: 'pub.leaflet.richtext.facet#italic' }

export type { Italic }

/** Facet feature for italic text */
const italic = /*#__PURE__*/ l.typedObject<Italic>(
  $nsid,
  'italic',
  /*#__PURE__*/ l.object({}),
)

export { italic }

/** Facet feature for a footnote reference */
type Footnote = {
  $type?: 'pub.leaflet.richtext.facet#footnote'
  footnoteId: string
  contentFacets?: Main[]
  contentPlaintext: string
}

export type { Footnote }

/** Facet feature for a footnote reference */
const footnote = /*#__PURE__*/ l.typedObject<Footnote>(
  $nsid,
  'footnote',
  /*#__PURE__*/ l.object({
    footnoteId: /*#__PURE__*/ l.string(),
    contentFacets: /*#__PURE__*/ l.optional(
      /*#__PURE__*/ l.array(/*#__PURE__*/ l.ref<Main>((() => main) as any)),
    ),
    contentPlaintext: /*#__PURE__*/ l.string(),
  }),
)

export { footnote }

/** Facet feature for mentioning an AT URI. */
type AtMention = {
  $type?: 'pub.leaflet.richtext.facet#atMention'
  atURI: l.UriString
}

export type { AtMention }

/** Facet feature for mentioning an AT URI. */
const atMention = /*#__PURE__*/ l.typedObject<AtMention>(
  $nsid,
  'atMention',
  /*#__PURE__*/ l.object({ atURI: /*#__PURE__*/ l.string({ format: 'uri' }) }),
)

export { atMention }

/** Specifies the sub-string range a facet feature applies to. Start index is inclusive, end index is exclusive. Indices are zero-indexed, counting bytes of the UTF-8 encoded text. NOTE: some languages, like Javascript, use UTF-16 or Unicode codepoints for string slice indexing; in these languages, convert to byte arrays before working with facets. */
type ByteSlice = {
  $type?: 'pub.leaflet.richtext.facet#byteSlice'
  byteEnd: number
  byteStart: number
}

export type { ByteSlice }

/** Specifies the sub-string range a facet feature applies to. Start index is inclusive, end index is exclusive. Indices are zero-indexed, counting bytes of the UTF-8 encoded text. NOTE: some languages, like Javascript, use UTF-16 or Unicode codepoints for string slice indexing; in these languages, convert to byte arrays before working with facets. */
const byteSlice = /*#__PURE__*/ l.typedObject<ByteSlice>(
  $nsid,
  'byteSlice',
  /*#__PURE__*/ l.object({
    byteEnd: /*#__PURE__*/ l.integer({ minimum: 0 }),
    byteStart: /*#__PURE__*/ l.integer({ minimum: 0 }),
  }),
)

export { byteSlice }

/** Facet feature for highlighted text. */
type Highlight = { $type?: 'pub.leaflet.richtext.facet#highlight' }

export type { Highlight }

/** Facet feature for highlighted text. */
const highlight = /*#__PURE__*/ l.typedObject<Highlight>(
  $nsid,
  'highlight',
  /*#__PURE__*/ l.object({}),
)

export { highlight }

/** Facet feature for underline markup */
type Underline = { $type?: 'pub.leaflet.richtext.facet#underline' }

export type { Underline }

/** Facet feature for underline markup */
const underline = /*#__PURE__*/ l.typedObject<Underline>(
  $nsid,
  'underline',
  /*#__PURE__*/ l.object({}),
)

export { underline }

/** Facet feature for mentioning a did. */
type DidMention = {
  $type?: 'pub.leaflet.richtext.facet#didMention'
  did: l.DidString
}

export type { DidMention }

/** Facet feature for mentioning a did. */
const didMention = /*#__PURE__*/ l.typedObject<DidMention>(
  $nsid,
  'didMention',
  /*#__PURE__*/ l.object({ did: /*#__PURE__*/ l.string({ format: 'did' }) }),
)

export { didMention }

/** Facet feature for strikethrough markup */
type Strikethrough = { $type?: 'pub.leaflet.richtext.facet#strikethrough' }

export type { Strikethrough }

/** Facet feature for strikethrough markup */
const strikethrough = /*#__PURE__*/ l.typedObject<Strikethrough>(
  $nsid,
  'strikethrough',
  /*#__PURE__*/ l.object({}),
)

export { strikethrough }
