/*
 * THIS FILE WAS GENERATED BY "@atproto/lex". DO NOT EDIT.
 */

import { l } from '@atproto/lex'
import * as PagesLinearDocument from './pages/linearDocument.defs'
import * as PagesCanvas from './pages/canvas.defs'
import * as LeafletPublication from './publication.defs'
import * as RepoStrongRef from '../../com/atproto/repo/strongRef.defs'

const $nsid = 'pub.leaflet.document'

type $nsid = typeof $nsid

export { $nsid }

/** Record containing a document */
type Main = {
  $type: 'pub.leaflet.document'
  tags?: string[]
  pages: (
    | l.$Typed<PagesLinearDocument.Main>
    | l.$Typed<PagesCanvas.Main>
    | l.Unknown$TypedObject
  )[]
  theme?: LeafletPublication.Theme
  title: string
  author: l.AtIdentifierString
  postRef?: RepoStrongRef.Main
  coverImage?: l.BlobRef
  description?: string
  preferences?: LeafletPublication.Preferences
  publication?: l.AtUriString
  publishedAt?: l.DatetimeString
}

export type { Main }

/** Record containing a document */
const main = /*#__PURE__*/ l.record<'tid', Main>(
  'tid',
  $nsid,
  /*#__PURE__*/ l.object({
    tags: /*#__PURE__*/ l.optional(
      /*#__PURE__*/ l.array(/*#__PURE__*/ l.string({ maxLength: 50 })),
    ),
    pages: /*#__PURE__*/ l.array(
      /*#__PURE__*/ l.typedUnion(
        [
          /*#__PURE__*/ l.typedRef<PagesLinearDocument.Main>(
            (() => PagesLinearDocument.main) as any,
          ),
          /*#__PURE__*/ l.typedRef<PagesCanvas.Main>(
            (() => PagesCanvas.main) as any,
          ),
        ],
        false,
      ),
    ),
    theme: /*#__PURE__*/ l.optional(
      /*#__PURE__*/ l.ref<LeafletPublication.Theme>(
        (() => LeafletPublication.theme) as any,
      ),
    ),
    title: /*#__PURE__*/ l.string({ maxLength: 5000, maxGraphemes: 500 }),
    author: /*#__PURE__*/ l.string({ format: 'at-identifier' }),
    postRef: /*#__PURE__*/ l.optional(
      /*#__PURE__*/ l.ref<RepoStrongRef.Main>(
        (() => RepoStrongRef.main) as any,
      ),
    ),
    coverImage: /*#__PURE__*/ l.optional(
      /*#__PURE__*/ l.blob({
        accept: ['image/png', 'image/jpeg', 'image/webp'],
        maxSize: 1000000,
      }),
    ),
    description: /*#__PURE__*/ l.optional(
      /*#__PURE__*/ l.string({ maxLength: 30000, maxGraphemes: 3000 }),
    ),
    preferences: /*#__PURE__*/ l.optional(
      /*#__PURE__*/ l.ref<LeafletPublication.Preferences>(
        (() => LeafletPublication.preferences) as any,
      ),
    ),
    publication: /*#__PURE__*/ l.optional(
      /*#__PURE__*/ l.string({ format: 'at-uri' }),
    ),
    publishedAt: /*#__PURE__*/ l.optional(
      /*#__PURE__*/ l.string({ format: 'datetime' }),
    ),
  }),
)

export { main }

const $type = $nsid

type $type = typeof $type

export { $type }

export const $isTypeOf = /*#__PURE__*/ main.isTypeOf.bind(main)
export const $build = /*#__PURE__*/ main.build.bind(main)
export const $assert = /*#__PURE__*/ main.assert.bind(main)
export const $check = /*#__PURE__*/ main.check.bind(main)
export const $cast = /*#__PURE__*/ main.cast.bind(main)
export const $ifMatches = /*#__PURE__*/ main.ifMatches.bind(main)
export const $matches = /*#__PURE__*/ main.matches.bind(main)
export const $parse = /*#__PURE__*/ main.parse.bind(main)
export const $safeParse = /*#__PURE__*/ main.safeParse.bind(main)
export const $validate = /*#__PURE__*/ main.validate.bind(main)
export const $safeValidate = /*#__PURE__*/ main.safeValidate.bind(main)
