/*
 * THIS FILE WAS GENERATED BY "@atproto/lex". DO NOT EDIT.
 */

import { l } from '@atproto/lex'
import * as PagesLinearDocument from './pages/linearDocument.defs'
import * as PagesCanvas from './pages/canvas.defs'
import * as LeafletPublication from './publication.defs'
import * as RepoStrongRef from '../../com/atproto/repo/strongRef.defs'

const $nsid = 'pub.leaflet.document'

export { $nsid }

/** Record containing a document */
type Main = {
  $type: 'pub.leaflet.document'
  tags?: string[]
  pages: (
    | l.$Typed<PagesLinearDocument.Main>
    | l.$Typed<PagesCanvas.Main>
    | l.Unknown$TypedObject
  )[]
  theme?: LeafletPublication.Theme
  title: string
  author: l.AtIdentifierString
  postRef?: RepoStrongRef.Main
  coverImage?: l.BlobRef
  description?: string
  preferences?: LeafletPublication.Preferences
  publication?: l.AtUriString
  publishedAt?: l.DatetimeString
}

export type { Main }

/** Record containing a document */
const main = l.record<'tid', Main>(
  'tid',
  $nsid,
  l.object({
    tags: l.optional(l.array(l.string({ maxLength: 50 }))),
    pages: l.array(
      l.typedUnion(
        [
          l.typedRef<PagesLinearDocument.Main>(
            (() => PagesLinearDocument.main) as any,
          ),
          l.typedRef<PagesCanvas.Main>((() => PagesCanvas.main) as any),
        ],
        false,
      ),
    ),
    theme: l.optional(
      l.ref<LeafletPublication.Theme>((() => LeafletPublication.theme) as any),
    ),
    title: l.string({ maxLength: 5000, maxGraphemes: 500 }),
    author: l.string({ format: 'at-identifier' }),
    postRef: l.optional(
      l.ref<RepoStrongRef.Main>((() => RepoStrongRef.main) as any),
    ),
    coverImage: l.optional(
      l.blob({
        accept: ['image/png', 'image/jpeg', 'image/webp'],
        maxSize: 1000000,
        allowLegacy: false,
      }),
    ),
    description: l.optional(l.string({ maxLength: 30000, maxGraphemes: 3000 })),
    preferences: l.optional(
      l.ref<LeafletPublication.Preferences>(
        (() => LeafletPublication.preferences) as any,
      ),
    ),
    publication: l.optional(l.string({ format: 'at-uri' })),
    publishedAt: l.optional(l.string({ format: 'datetime' })),
  }),
)

export { main }

export const $isTypeOf = /*#__PURE__*/ main.isTypeOf.bind(main),
  $build = /*#__PURE__*/ main.build.bind(main),
  $type = /*#__PURE__*/ main.$type
export const $assert = /*#__PURE__*/ main.assert.bind(main),
  $check = /*#__PURE__*/ main.check.bind(main),
  $cast = /*#__PURE__*/ main.cast.bind(main),
  $ifMatches = /*#__PURE__*/ main.ifMatches.bind(main),
  $matches = /*#__PURE__*/ main.matches.bind(main),
  $parse = /*#__PURE__*/ main.parse.bind(main),
  $safeParse = /*#__PURE__*/ main.safeParse.bind(main),
  $validate = /*#__PURE__*/ main.validate.bind(main),
  $safeValidate = /*#__PURE__*/ main.safeValidate.bind(main)
