/*
 * THIS FILE WAS GENERATED BY "@atproto/lex". DO NOT EDIT.
 */

import { l } from '@atproto/lex'
import * as ThemeColor from './theme/color.defs'
import * as ThemeBackgroundImage from './theme/backgroundImage.defs'

const $nsid = 'pub.leaflet.publication'

export { $nsid }

/** Record declaring a publication */
type Main = {
  $type: 'pub.leaflet.publication'
  icon?: l.BlobRef
  name: string
  theme?: Theme
  base_path?: string
  description?: string
  preferences?: Preferences
}

export type { Main }

/** Record declaring a publication */
const main = l.record<'tid', Main>(
  'tid',
  $nsid,
  l.object({
    icon: l.optional(
      l.blob({ accept: ['image/*'], maxSize: 1000000, allowLegacy: false }),
    ),
    name: l.string({ maxLength: 2000 }),
    theme: l.optional(l.ref<Theme>((() => theme) as any)),
    base_path: l.optional(l.string()),
    description: l.optional(l.string({ maxLength: 2000 })),
    preferences: l.optional(l.ref<Preferences>((() => preferences) as any)),
  }),
)

export { main }

export const $isTypeOf = /*#__PURE__*/ main.isTypeOf.bind(main),
  $build = /*#__PURE__*/ main.build.bind(main),
  $type = /*#__PURE__*/ main.$type
export const $assert = /*#__PURE__*/ main.assert.bind(main),
  $check = /*#__PURE__*/ main.check.bind(main),
  $cast = /*#__PURE__*/ main.cast.bind(main),
  $ifMatches = /*#__PURE__*/ main.ifMatches.bind(main),
  $matches = /*#__PURE__*/ main.matches.bind(main),
  $parse = /*#__PURE__*/ main.parse.bind(main),
  $safeParse = /*#__PURE__*/ main.safeParse.bind(main),
  $validate = /*#__PURE__*/ main.validate.bind(main),
  $safeValidate = /*#__PURE__*/ main.safeValidate.bind(main)

type Theme = {
  $type?: 'pub.leaflet.publication#theme'
  primary?:
    | l.$Typed<ThemeColor.Rgba>
    | l.$Typed<ThemeColor.Rgb>
    | l.Unknown$TypedObject
  bodyFont?: string
  pageWidth?: number
  accentText?:
    | l.$Typed<ThemeColor.Rgba>
    | l.$Typed<ThemeColor.Rgb>
    | l.Unknown$TypedObject
  headingFont?: string
  pageBackground?:
    | l.$Typed<ThemeColor.Rgba>
    | l.$Typed<ThemeColor.Rgb>
    | l.Unknown$TypedObject
  backgroundColor?:
    | l.$Typed<ThemeColor.Rgba>
    | l.$Typed<ThemeColor.Rgb>
    | l.Unknown$TypedObject
  backgroundImage?: ThemeBackgroundImage.Main
  accentBackground?:
    | l.$Typed<ThemeColor.Rgba>
    | l.$Typed<ThemeColor.Rgb>
    | l.Unknown$TypedObject
  showPageBackground?: boolean
}

export type { Theme }

const theme = l.typedObject<Theme>(
  $nsid,
  'theme',
  l.object({
    primary: l.optional(
      l.typedUnion(
        [
          l.typedRef<ThemeColor.Rgba>((() => ThemeColor.rgba) as any),
          l.typedRef<ThemeColor.Rgb>((() => ThemeColor.rgb) as any),
        ],
        false,
      ),
    ),
    bodyFont: l.optional(l.string({ maxLength: 100 })),
    pageWidth: l.optional(l.integer({ maximum: 1600, minimum: 0 })),
    accentText: l.optional(
      l.typedUnion(
        [
          l.typedRef<ThemeColor.Rgba>((() => ThemeColor.rgba) as any),
          l.typedRef<ThemeColor.Rgb>((() => ThemeColor.rgb) as any),
        ],
        false,
      ),
    ),
    headingFont: l.optional(l.string({ maxLength: 100 })),
    pageBackground: l.optional(
      l.typedUnion(
        [
          l.typedRef<ThemeColor.Rgba>((() => ThemeColor.rgba) as any),
          l.typedRef<ThemeColor.Rgb>((() => ThemeColor.rgb) as any),
        ],
        false,
      ),
    ),
    backgroundColor: l.optional(
      l.typedUnion(
        [
          l.typedRef<ThemeColor.Rgba>((() => ThemeColor.rgba) as any),
          l.typedRef<ThemeColor.Rgb>((() => ThemeColor.rgb) as any),
        ],
        false,
      ),
    ),
    backgroundImage: l.optional(
      l.ref<ThemeBackgroundImage.Main>(
        (() => ThemeBackgroundImage.main) as any,
      ),
    ),
    accentBackground: l.optional(
      l.typedUnion(
        [
          l.typedRef<ThemeColor.Rgba>((() => ThemeColor.rgba) as any),
          l.typedRef<ThemeColor.Rgb>((() => ThemeColor.rgb) as any),
        ],
        false,
      ),
    ),
    showPageBackground: l.optional(l.withDefault(l.boolean(), false)),
  }),
)

export { theme }

type Preferences = {
  $type?: 'pub.leaflet.publication#preferences'
  showComments?: boolean
  showMentions?: boolean
  showPrevNext?: boolean
  showInDiscover?: boolean
  showRecommends?: boolean
}

export type { Preferences }

const preferences = l.typedObject<Preferences>(
  $nsid,
  'preferences',
  l.object({
    showComments: l.optional(l.withDefault(l.boolean(), true)),
    showMentions: l.optional(l.withDefault(l.boolean(), true)),
    showPrevNext: l.optional(l.withDefault(l.boolean(), true)),
    showInDiscover: l.optional(l.withDefault(l.boolean(), true)),
    showRecommends: l.optional(l.withDefault(l.boolean(), true)),
  }),
)

export { preferences }
