/*
 * THIS FILE WAS GENERATED BY "@atproto/lex". DO NOT EDIT.
 */

import { l } from '@atproto/lex'
import * as ThemeColor from './theme/color.defs'
import * as ThemeBackgroundImage from './theme/backgroundImage.defs'

const $nsid = 'pub.leaflet.publication'

type $nsid = typeof $nsid

export { $nsid }

/** Record declaring a publication */
type Main = {
  $type: 'pub.leaflet.publication'
  icon?: l.BlobRef
  name: string
  theme?: Theme
  base_path?: string
  description?: string
  preferences?: Preferences
}

export type { Main }

/** Record declaring a publication */
const main = /*#__PURE__*/ l.record<'tid', Main>(
  'tid',
  $nsid,
  /*#__PURE__*/ l.object({
    icon: /*#__PURE__*/ l.optional(
      /*#__PURE__*/ l.blob({ accept: ['image/*'], maxSize: 1000000 }),
    ),
    name: /*#__PURE__*/ l.string({ maxLength: 2000 }),
    theme: /*#__PURE__*/ l.optional(
      /*#__PURE__*/ l.ref<Theme>((() => theme) as any),
    ),
    base_path: /*#__PURE__*/ l.optional(/*#__PURE__*/ l.string()),
    description: /*#__PURE__*/ l.optional(
      /*#__PURE__*/ l.string({ maxLength: 2000 }),
    ),
    preferences: /*#__PURE__*/ l.optional(
      /*#__PURE__*/ l.ref<Preferences>((() => preferences) as any),
    ),
  }),
)

export { main }

const $type = $nsid

type $type = typeof $type

export { $type }

export const $isTypeOf = /*#__PURE__*/ main.isTypeOf.bind(main)
export const $build = /*#__PURE__*/ main.build.bind(main)
export const $assert = /*#__PURE__*/ main.assert.bind(main)
export const $check = /*#__PURE__*/ main.check.bind(main)
export const $cast = /*#__PURE__*/ main.cast.bind(main)
export const $ifMatches = /*#__PURE__*/ main.ifMatches.bind(main)
export const $matches = /*#__PURE__*/ main.matches.bind(main)
export const $parse = /*#__PURE__*/ main.parse.bind(main)
export const $safeParse = /*#__PURE__*/ main.safeParse.bind(main)
export const $validate = /*#__PURE__*/ main.validate.bind(main)
export const $safeValidate = /*#__PURE__*/ main.safeValidate.bind(main)

type Theme = {
  $type?: 'pub.leaflet.publication#theme'
  primary?:
    l.$Typed<ThemeColor.Rgba> | l.$Typed<ThemeColor.Rgb> | l.Unknown$TypedObject
  bodyFont?: string
  pageWidth?: number
  accentText?:
    l.$Typed<ThemeColor.Rgba> | l.$Typed<ThemeColor.Rgb> | l.Unknown$TypedObject
  headingFont?: string
  pageBackground?:
    l.$Typed<ThemeColor.Rgba> | l.$Typed<ThemeColor.Rgb> | l.Unknown$TypedObject
  backgroundColor?:
    l.$Typed<ThemeColor.Rgba> | l.$Typed<ThemeColor.Rgb> | l.Unknown$TypedObject
  backgroundImage?: ThemeBackgroundImage.Main
  accentBackground?:
    l.$Typed<ThemeColor.Rgba> | l.$Typed<ThemeColor.Rgb> | l.Unknown$TypedObject
  showPageBackground?: boolean
}

export type { Theme }

const theme = /*#__PURE__*/ l.typedObject<Theme>(
  $nsid,
  'theme',
  /*#__PURE__*/ l.object({
    primary: /*#__PURE__*/ l.optional(
      /*#__PURE__*/ l.typedUnion(
        [
          /*#__PURE__*/ l.typedRef<ThemeColor.Rgba>(
            (() => ThemeColor.rgba) as any,
          ),
          /*#__PURE__*/ l.typedRef<ThemeColor.Rgb>(
            (() => ThemeColor.rgb) as any,
          ),
        ],
        false,
      ),
    ),
    bodyFont: /*#__PURE__*/ l.optional(
      /*#__PURE__*/ l.string({ maxLength: 100 }),
    ),
    pageWidth: /*#__PURE__*/ l.optional(
      /*#__PURE__*/ l.integer({ maximum: 1600, minimum: 0 }),
    ),
    accentText: /*#__PURE__*/ l.optional(
      /*#__PURE__*/ l.typedUnion(
        [
          /*#__PURE__*/ l.typedRef<ThemeColor.Rgba>(
            (() => ThemeColor.rgba) as any,
          ),
          /*#__PURE__*/ l.typedRef<ThemeColor.Rgb>(
            (() => ThemeColor.rgb) as any,
          ),
        ],
        false,
      ),
    ),
    headingFont: /*#__PURE__*/ l.optional(
      /*#__PURE__*/ l.string({ maxLength: 100 }),
    ),
    pageBackground: /*#__PURE__*/ l.optional(
      /*#__PURE__*/ l.typedUnion(
        [
          /*#__PURE__*/ l.typedRef<ThemeColor.Rgba>(
            (() => ThemeColor.rgba) as any,
          ),
          /*#__PURE__*/ l.typedRef<ThemeColor.Rgb>(
            (() => ThemeColor.rgb) as any,
          ),
        ],
        false,
      ),
    ),
    backgroundColor: /*#__PURE__*/ l.optional(
      /*#__PURE__*/ l.typedUnion(
        [
          /*#__PURE__*/ l.typedRef<ThemeColor.Rgba>(
            (() => ThemeColor.rgba) as any,
          ),
          /*#__PURE__*/ l.typedRef<ThemeColor.Rgb>(
            (() => ThemeColor.rgb) as any,
          ),
        ],
        false,
      ),
    ),
    backgroundImage: /*#__PURE__*/ l.optional(
      /*#__PURE__*/ l.ref<ThemeBackgroundImage.Main>(
        (() => ThemeBackgroundImage.main) as any,
      ),
    ),
    accentBackground: /*#__PURE__*/ l.optional(
      /*#__PURE__*/ l.typedUnion(
        [
          /*#__PURE__*/ l.typedRef<ThemeColor.Rgba>(
            (() => ThemeColor.rgba) as any,
          ),
          /*#__PURE__*/ l.typedRef<ThemeColor.Rgb>(
            (() => ThemeColor.rgb) as any,
          ),
        ],
        false,
      ),
    ),
    showPageBackground: /*#__PURE__*/ l.optional(
      /*#__PURE__*/ l.withDefault(/*#__PURE__*/ l.boolean(), false),
    ),
  }),
)

export { theme }

type Preferences = {
  $type?: 'pub.leaflet.publication#preferences'
  showComments?: boolean
  showMentions?: boolean
  showPrevNext?: boolean
  showInDiscover?: boolean
  showRecommends?: boolean
}

export type { Preferences }

const preferences = /*#__PURE__*/ l.typedObject<Preferences>(
  $nsid,
  'preferences',
  /*#__PURE__*/ l.object({
    showComments: /*#__PURE__*/ l.optional(
      /*#__PURE__*/ l.withDefault(/*#__PURE__*/ l.boolean(), true),
    ),
    showMentions: /*#__PURE__*/ l.optional(
      /*#__PURE__*/ l.withDefault(/*#__PURE__*/ l.boolean(), true),
    ),
    showPrevNext: /*#__PURE__*/ l.optional(
      /*#__PURE__*/ l.withDefault(/*#__PURE__*/ l.boolean(), true),
    ),
    showInDiscover: /*#__PURE__*/ l.optional(
      /*#__PURE__*/ l.withDefault(/*#__PURE__*/ l.boolean(), true),
    ),
    showRecommends: /*#__PURE__*/ l.optional(
      /*#__PURE__*/ l.withDefault(/*#__PURE__*/ l.boolean(), true),
    ),
  }),
)

export { preferences }
