/*
 * THIS FILE WAS GENERATED BY "@atproto/lex". DO NOT EDIT.
 */

import { l } from '@atproto/lex'
import * as BlocksIframe from '../blocks/iframe.defs'
import * as BlocksText from '../blocks/text.defs'
import * as BlocksBlockquote from '../blocks/blockquote.defs'
import * as BlocksHeader from '../blocks/header.defs'
import * as BlocksImage from '../blocks/image.defs'
import * as BlocksUnorderedList from '../blocks/unorderedList.defs'
import * as BlocksOrderedList from '../blocks/orderedList.defs'
import * as BlocksWebsite from '../blocks/website.defs'
import * as BlocksMath from '../blocks/math.defs'
import * as BlocksCode from '../blocks/code.defs'
import * as BlocksHorizontalRule from '../blocks/horizontalRule.defs'
import * as BlocksBskyPost from '../blocks/bskyPost.defs'
import * as BlocksPage from '../blocks/page.defs'
import * as BlocksPoll from '../blocks/poll.defs'
import * as BlocksButton from '../blocks/button.defs'

const $nsid = 'pub.leaflet.pages.canvas'

type $nsid = typeof $nsid

export { $nsid }

type Main = { $type?: 'pub.leaflet.pages.canvas'; id?: string; blocks: Block[] }

export type { Main }

const main = /*#__PURE__*/ l.typedObject<Main>(
  $nsid,
  'main',
  /*#__PURE__*/ l.object({
    id: /*#__PURE__*/ l.optional(/*#__PURE__*/ l.string()),
    blocks: /*#__PURE__*/ l.array(
      /*#__PURE__*/ l.ref<Block>((() => block) as any),
    ),
  }),
)

export { main }

const $type = $nsid

type $type = typeof $type

export { $type }

export const $isTypeOf = /*#__PURE__*/ main.isTypeOf.bind(main)
export const $build = /*#__PURE__*/ main.build.bind(main)
export const $assert = /*#__PURE__*/ main.assert.bind(main)
export const $check = /*#__PURE__*/ main.check.bind(main)
export const $cast = /*#__PURE__*/ main.cast.bind(main)
export const $ifMatches = /*#__PURE__*/ main.ifMatches.bind(main)
export const $matches = /*#__PURE__*/ main.matches.bind(main)
export const $parse = /*#__PURE__*/ main.parse.bind(main)
export const $safeParse = /*#__PURE__*/ main.safeParse.bind(main)
export const $validate = /*#__PURE__*/ main.validate.bind(main)
export const $safeValidate = /*#__PURE__*/ main.safeValidate.bind(main)

type Block = {
  $type?: 'pub.leaflet.pages.canvas#block'
  x: number
  y: number
  block:
    | l.$Typed<BlocksIframe.Main>
    | l.$Typed<BlocksText.Main>
    | l.$Typed<BlocksBlockquote.Main>
    | l.$Typed<BlocksHeader.Main>
    | l.$Typed<BlocksImage.Main>
    | l.$Typed<BlocksUnorderedList.Main>
    | l.$Typed<BlocksOrderedList.Main>
    | l.$Typed<BlocksWebsite.Main>
    | l.$Typed<BlocksMath.Main>
    | l.$Typed<BlocksCode.Main>
    | l.$Typed<BlocksHorizontalRule.Main>
    | l.$Typed<BlocksBskyPost.Main>
    | l.$Typed<BlocksPage.Main>
    | l.$Typed<BlocksPoll.Main>
    | l.$Typed<BlocksButton.Main>
    | l.Unknown$TypedObject
  width: number
  height?: number

  /**
   * The rotation of the block in degrees
   */
  rotation?: number
}

export type { Block }

const block = /*#__PURE__*/ l.typedObject<Block>(
  $nsid,
  'block',
  /*#__PURE__*/ l.object({
    x: /*#__PURE__*/ l.integer(),
    y: /*#__PURE__*/ l.integer(),
    block: /*#__PURE__*/ l.typedUnion(
      [
        /*#__PURE__*/ l.typedRef<BlocksIframe.Main>(
          (() => BlocksIframe.main) as any,
        ),
        /*#__PURE__*/ l.typedRef<BlocksText.Main>(
          (() => BlocksText.main) as any,
        ),
        /*#__PURE__*/ l.typedRef<BlocksBlockquote.Main>(
          (() => BlocksBlockquote.main) as any,
        ),
        /*#__PURE__*/ l.typedRef<BlocksHeader.Main>(
          (() => BlocksHeader.main) as any,
        ),
        /*#__PURE__*/ l.typedRef<BlocksImage.Main>(
          (() => BlocksImage.main) as any,
        ),
        /*#__PURE__*/ l.typedRef<BlocksUnorderedList.Main>(
          (() => BlocksUnorderedList.main) as any,
        ),
        /*#__PURE__*/ l.typedRef<BlocksOrderedList.Main>(
          (() => BlocksOrderedList.main) as any,
        ),
        /*#__PURE__*/ l.typedRef<BlocksWebsite.Main>(
          (() => BlocksWebsite.main) as any,
        ),
        /*#__PURE__*/ l.typedRef<BlocksMath.Main>(
          (() => BlocksMath.main) as any,
        ),
        /*#__PURE__*/ l.typedRef<BlocksCode.Main>(
          (() => BlocksCode.main) as any,
        ),
        /*#__PURE__*/ l.typedRef<BlocksHorizontalRule.Main>(
          (() => BlocksHorizontalRule.main) as any,
        ),
        /*#__PURE__*/ l.typedRef<BlocksBskyPost.Main>(
          (() => BlocksBskyPost.main) as any,
        ),
        /*#__PURE__*/ l.typedRef<BlocksPage.Main>(
          (() => BlocksPage.main) as any,
        ),
        /*#__PURE__*/ l.typedRef<BlocksPoll.Main>(
          (() => BlocksPoll.main) as any,
        ),
        /*#__PURE__*/ l.typedRef<BlocksButton.Main>(
          (() => BlocksButton.main) as any,
        ),
      ],
      false,
    ),
    width: /*#__PURE__*/ l.integer(),
    height: /*#__PURE__*/ l.optional(/*#__PURE__*/ l.integer()),
    rotation: /*#__PURE__*/ l.optional(/*#__PURE__*/ l.integer()),
  }),
)

export { block }

type Quote = {
  $type?: 'pub.leaflet.pages.canvas#quote'
  end: Position
  start: Position
}

export type { Quote }

const quote = /*#__PURE__*/ l.typedObject<Quote>(
  $nsid,
  'quote',
  /*#__PURE__*/ l.object({
    end: /*#__PURE__*/ l.ref<Position>((() => position) as any),
    start: /*#__PURE__*/ l.ref<Position>((() => position) as any),
  }),
)

export { quote }

type Position = {
  $type?: 'pub.leaflet.pages.canvas#position'
  block: number[]
  offset: number
}

export type { Position }

const position = /*#__PURE__*/ l.typedObject<Position>(
  $nsid,
  'position',
  /*#__PURE__*/ l.object({
    block: /*#__PURE__*/ l.array(/*#__PURE__*/ l.integer()),
    offset: /*#__PURE__*/ l.integer(),
  }),
)

export { position }

const textAlignLeft = /*#__PURE__*/ l.token($nsid, 'textAlignLeft')

export { textAlignLeft }

const TextAlignLeft = /*#__PURE__*/ textAlignLeft.value

type TextAlignLeft = typeof TextAlignLeft

export { TextAlignLeft }

const textAlignRight = /*#__PURE__*/ l.token($nsid, 'textAlignRight')

export { textAlignRight }

const TextAlignRight = /*#__PURE__*/ textAlignRight.value

type TextAlignRight = typeof TextAlignRight

export { TextAlignRight }

const textAlignCenter = /*#__PURE__*/ l.token($nsid, 'textAlignCenter')

export { textAlignCenter }

const TextAlignCenter = /*#__PURE__*/ textAlignCenter.value

type TextAlignCenter = typeof TextAlignCenter

export { TextAlignCenter }
