/*
 * THIS FILE WAS GENERATED BY "@atproto/lex". DO NOT EDIT.
 */

export * from './linearDocument.defs'
export * as $defs from './linearDocument.defs'
export { main as default } from './linearDocument.defs'
