name: build

on:
  push:
    branches:
      - main
  release:

permissions:
  contents: write
  packages: write

env:
  TAG: ${{ github.ref_name }}

jobs:
  build-image:
    name: "Build Image and push to Github Container Registry"
    runs-on: ubuntu-latest

    steps:
      - name: Clone
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.PAT }}

      - name: build-image
        id: build-image
        run: |
          docker buildx build \
          --push \
          --platform linux/amd64,linux/arm64 \
          --tag ghcr.io/patrickjmcd/pmcd.dev:${{ github.sha }} \
          .

  update-k8s-flux:
    name: "Update k8s-flux"
    runs-on: ubuntu-latest
    needs: build-image
    steps:
      - uses: actions/checkout@v3
        with:
          repository: "patrickjmcd/k8s-argo"
          path: "k8s-argo"
          token: ${{ secrets.PAT }}

      - name: Setup Kustomize
        uses: imranismail/setup-kustomize@v1

      - name: Update Kubernetes resources & commit & push
        run: |
          cd k8s-argo/apps/pmcd.dev
          kustomize edit set image pmcd-dev=ghcr.io/patrickjmcd/pmcd.dev:${{ github.sha }}
          cat kustomization.yaml
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git commit -am "Bump docker tag"
          git push
